Cypress.Commands.add('assertPreenchimentoDeFormESubmit', () =>{
  cy.get('#nomeAnuncio').should('be.empty')
  cy.get('#nome').should('be.empty')
  cy.get('#investimentoDiario').should('be.empty')
  cy.get('#selecoes').find('option')
      .and('contain', 'Selecionar') 
      .should('be.selected')
  cy.get('#pacote03').should('not.be.checked')
  cy.get('#pacote03').should('not.be.checked')
  cy.get('#mensal').should('not.be.checked')
  cy.get('[data-cy=start-cy]').should('be.empty')
  cy.get('[data-cy=end-cy]').should('be.empty')
  cy.get('#projecaoAproximada').should('be.visible')
     .and('contain', 'Essa é a projeção aproximada')
})
